### ISSUE TITLE
perl 5.8.8 is supported?

### ISSUE THREAD

**Issue by x09** [Robertof/perl-www-telegram-botapi#1]
I try use with perl 5.8.8, but get mistake only.. Can you help me?

```
use strict;
use WWW::Telegram::BotAPI;
my $api = WWW::Telegram::BotAPI->new (
        token => '128914425:my_token-my_token-my_token-my_token-my_token-my_token',
        force_lwp => 1,
        async => 0
    );
    $api->api_request ('getMe');
    # Uploading files is easier than ever.
    $api->sendPhoto ({
        chat_id => 123456,
        photo   => {
            file => "/path/to/png/1441213424_178_Download.png"
        },
        caption => "Look at my cool photo!"
    });
```

try ./bot.pl and get

ERROR: 400 Bad Request at /usr/lib/perl5/site_perl/5.8.8/WWW/Telegram/BotAPI.pm line 139.
        (in cleanup) ERROR: 404 Not Found at /usr/lib/perl5/site_perl/5.8.8/WWW/Telegram/BotAPI.pm line 139.

what i can do wrong?

**Comment by Robertof** [comment]
Hello,

thanks for your report! I tried the module with Perl v5.8.8 (_which is almost 10 years old!_) and there was indeed a problem.
Basically, Perl was calling my `AUTOLOAD` subroutine when destroying the module object. This happened because I didn't implement a `DESTROY` subroutine for cleanup.

I just released a new version (`v0.02`) which fixes this issue. It should be available on CPAN shortly.

About your specific problem (the `HTTP 400 Bad Request`), it looks like you are doing something wrong. Please check the following:
- Ensure that the token you are using is valid and updated. (to test, make a request with your browser to `https://api.telegram.org/botYOUR_TOKEN_GOES_HERE/getMe` and see if it works)
- Ensure that the parameters you are passing to the requested method are valid. You can check for this in the [official Bots API documentation](https://core.telegram.org/bots/api#available-methods). If you are using the example you pasted, then it obviously won't work because `chat_id` is not set to a real chat ID (123456)! Methods to retrieve the correct chat ID to use are described in the documentation linked before.

By the way, there's no need to use `force_lwp` and `async` in this case.

**Comment by x09** [comment]
Hi!
I install 0.2 version. All fine.

```
use strict;
use warnings;
use utf8;
use WWW::Telegram::BotAPI;
use Data::Dumper;

my $api = WWW::Telegram::BotAPI->new (
        token => 'my-token-here-my-token-here-my-token-here-my-token-here-my-token-here',
        force_lwp => 1,
        async => 0
    );
    print $api->getMe->{result}{username} , '-' , $api->getMe->{result}{id} ;
```

return bot username and chat_id  without any errors!

p.s. Can you write simple bot implementation, for example ? 
Bot with one command, user send 'what your name?', bot answer - 'my name is'.$api->getMe->{result}{username}. It would have really help to me for understanding!

my terrible example below :)

```
use strict;
use warnings;
use utf8;
use WWW::Telegram::BotAPI;
use Data::Dumper;

my $api = WWW::Telegram::BotAPI->new (
        token => 'my_token_here-my_token_here-my_token_here-my_token_here-my_token_here-',
        force_lwp => 1,
        async => 0
    );

$api->getUpdates;
my $last_id= $api->getUpdates->{result}[-1]{update_id};
#print $last_id; exit;
while ( 1 ) {
    if ($api->getUpdates->{result}[-1]{update_id}>$last_id) {
    print $last_id."\n";
            $api->SendMessage
                ({
                chat_id => $api->getUpdates->{result}[-1]{message}{from}{id},
                text    => 'Hello world!'
                });
        $api->getUpdates;
        $last_id++;

        }
sleep 1;
}
```

**Comment by Robertof** [comment]
[Here it is](https://gist.github.com/Robertof/d9358b80d95850e2eb34).

I'm closing the issue since the original problem has been resolved.
